talaia-labs/rust-teos

- teos/src/bitcoin_cli.rs
- teos/src/carrier.rs
- teos/src/chain_monitor.rs
- teos/src/config.rs
- teos/src/dbm.rs
- teos/src/extended_appointment.rs
- teos/src/gatekeeper.rs
- teos/src/lib.rs
- teos/src/main.rs
- teos/src/responder.rs
- teos/src/rpc_errors.rs
- teos/src/watcher.rs
Watcher:
- Modifies ``LocatorCache`` to hold ``BlockHash`` instead of ``BlockHeader``. The headers were not really used for anything aside from checking the hash chain.
- Refactors for loop to use iterators.
Carrier:
- Renames Receipt to DeliveryReceipt
Config:
- Makes `Config::verify` use `bitcoin::network::constants::Network` so code is cleaner and data is parsed from an enum instead of from Strings.
DBM:
- Updates DBM method visibility. Also store_key -> store_tower_key
> Adds teos crate docs plus some smalls fixes

- .gitignore
- teos-common/src/appointment.rs
- teos-common/src/lib.rs
- teos/Cargo.toml
- teos/build.rs
- teos/proto/teos/appointment.proto
- teos/proto/teos/tower_services.proto
- teos/proto/teos/user.proto
- teos/src/api.rs
- teos/src/chain_monitor.rs
- teos/src/config.rs
- teos/src/dbm.rs
- teos/src/extended_appointment.rs
- teos/src/gatekeeper.rs
- teos/src/lib.rs
- teos/src/main.rs
- teos/src/responder.rs
- teos/src/test_utils.rs
- teos/src/watcher.rs
Adds the `InternalAPI`, a gRPC server that interfaces with the tower internals.
The `InternalAPI` is the only endpoint to send data to the tower, it has two main interfaces, the public and the private.
The public interface is reachable by users via any tower client, and contains the functionality required to register and send/retrieve appointments to/from the tower.
The private interface is reachable by the tower admin via the gRPC client (teos-cli) and contains functionality to manage and interact with the tower from an admin perspective.
The major change w.r.t the existing codebase is that the main components are not `Arc/Mutex` instead of `Rc/RefCell` given the gRPC server introduces a new thread, so components need to be safely shared between threads.
Some minor changes include how …
> Adds the gRPC server to the tower (InternalAPI)

- teos/src/cli.rs
- teos/src/cli_config.rs
- teos/src/config.rs
- teos/src/lib.rs
- teos/src/main.rs
- teos/src/proto_fmt.rs
Adds teos-cli alongside it's own configuration parsing. `config.rs` has been reformatted so `cli-config.rs` can reuse as much functionality as possible.
`main.rs` now runs two different gRPC servers, a public one (using `rpc_bind` and `rpc_port`) where `teos-cli connects` to and an internal one (using `internal_api_bind` and `internal_api_port`) where the public APIs will connect to.
> Adds teos-cli and reformats conf.rs

- teos-common/src/errors.rs
- teos/build.rs
- teos/src/api/http.rs
- teos/src/api/mod.rs
Makes proto messages derive serde so they can be reused as requests / responses for the API. WIth that, all custom messages created for `api::http` are not needed anymore and can be therefore removed.
Reworks ApiError and make rejection functions actually return a rejection (and therefor Err). Also revamps `api::htto::handle_rejection` so uncatch rejections can be passed through (which was the original intention, I just couldn't figure out how to do so).
Finally, adds serialization functions for the things need custom serde, like vector of locators (Vec<Vec<u8>> -> Vec<String>) and appointment status. The later is due to how tonic deals with enums internally.
> Simplify apis

- teos-common/Cargo.toml
- teos-common/src/appointment.rs
- teos-common/src/errors.rs
- teos-common/src/lib.rs
- teos/Cargo.toml
- teos/build.rs
- teos/src/api/http.rs
- teos/src/api/internal.rs
- teos/src/api/mod.rs
- teos/src/config.rs
- teos/src/main.rs
- teos/src/test_utils.rs
Adds an HTTP REST API clients can connect to interact with the tower. The API serves an HTTP server and connects with the `InternalAPI` via gRPC.
The methods exposed to users match the `PublicTowerServices` from `api::internal::InternalAPI`, that is, currently:
- register
- add_appointment
- get_appointment
- get_subscription_info
> Adds public API (HTTP)

- teos/src/responder.rs
- teos/src/watcher.rs
Appointments were not being properly deleted when passed from the `Watcher` to the `Responder`. Wether the `Responder` accepted the job or not was not being checked, meaning the `Appointment` was being deleted as if it was invalid.
This mainly means that once an appointment was passed to the `Responder` it was not only being deleted from memory, but also from the database. This produced a cascade deletion, so the entry was completely wiped from from everywhere but the `Responder`'s memory.
Adds `deleted_appointment_from_memory` to the `Watcher` and checks the `DeliveryReceipt` when handling an appointment to the `Responder`. If the appointment is accepted, then it is only deleted from the `Watcher`'s memory, delegating the cascade deletion to the `Responder` once it is finalized. 
Also …
> Fixes appointment deletion when passed to the Responder

- teos/src/carrier.rs
- teos/src/chain_monitor.rs
- teos/src/dbm.rs
- teos/src/extended_appointment.rs
- teos/src/gatekeeper.rs
- teos/src/main.rs
- teos/src/responder.rs
- teos/src/test_utils.rs
- teos/src/watcher.rs
Bootstraps the tower from data backed-up in the database from a previous run of the system (if any is found) otherwise runs it "fresh".
The DBM is highly simplified and made more robust. First, unused methods are removed (or moved to the test modules if used for testing purposes). Furthermore, queries that need to be executed in batch are reworked so they are sent as a single database transaction (through potentially multiple queries). This is the case of data deletion for instance, where once an appointment / trackers is deleted the corresponding user needs to be updated.
Components that back up data in the database (`Watcher`, `Responder` and `Gatekeeper`) and initialized pulling that data from it. The system is therefore bootstrapped in three phases:
- First the components are created …
> Bootstraps from persisted data

- teos/proto/teos/appointment.proto
- teos/src/dbm.rs
- teos/src/responder.rs
- teos/src/test_utils.rs
- teos/src/watcher.rs
Appointment locators where also stored as part of trackers. However, they were not necessary (nor generally used).
The only case where locators were read from trackers was when computing the `subscription_info` for a given user.
Data is now pulled from the database (through `load_locator`) in that case. This also means that `Breach` does not
need to store a locator either.
> Removes locator from Trackers

- teos/proto/teos/appointment.proto
- teos/proto/teos/tower_services.proto
- teos/proto/teos/user.proto
- teos/src/lib.rs
rust-teos protos are not compatible with python-teos, however, they were using the same version.
Updates the version to make clear they are not compatible.
> Bump teos proto version

- teos/src/test_utils.rs
`test_utils::Blockchain` has some methods that are currently not being used (dead code).
The code comes from `lightning-block-sync` and may be useful in the future.
> Allows dead code in test_utils::Blockchain

- teos/src/chain_monitor.rs
- teos/src/config.rs
- teos/src/main.rs
`polling_delta` must have been a config parameter. Modifies the type from `u64` to `u16` since it does not make sense to poll every more than 10 min (value is in secs).
The value has been defaulted to 1 min since polling often is recommendable.
> Adds ChainMonitor's polling_delta as a config parameter

- teos/src/conf_template.toml
- teos/src/config.rs
- teos/src/main.rs
The default rpc ports for mainnet, testnet and signet were wrong. Set the up correctly.
Furthermore, return a more friendly error message when the rpc username or password is incorrect.
> Fix startup defaults

- teos-common/src/cryptography.rs
- teos/src/carrier.rs
- teos/src/dbm.rs
- teos/src/responder.rs
- teos/src/test_utils.rs
The codebase had different ways of performing bitcoin serde:
- Using bitcoin::consensus::{encode, decode}
- Using bitcoin::util::psbt::serialize::{Deserialize, Serialize};
The former feels like a cleaner way of doing so, normalizing all the appearances.
> Uses serde functions from bitcoin crate in a consistent manner

- .github/workflows/build.yaml
- teos/src/extended_appointment.rs
This PR adds a new job named `lint` that runs `cargo fmt` on the project and then `cargo clippy`. This won't apply fixes, but will only report them and fail the workflow if there were any.
Further improvements:
- We can have the `build` job depending on `lint`.
> Add rustfmt and clippy to the CI

- README.md
- teos/Cargo.toml
- teos/src/api/mod.rs
- teos/src/api/tor.rs
- teos/src/conf_template.toml
- teos/src/config.rs
- teos/src/main.rs
Added a new file 'tor.rs' to the 'api' folder which uses the torut library to create an onion hidden service. It accomplishes this by calling out to a running tor daemon, on the same machine, through it's control port. I added a dependency to the 'anyhow' library, if we'd rather not added that, just let me know and I can figure out how to pull that library out from my changes. I added some basic unit tests, but if you believe this needs more coverage, again, just let me know. Personally think adding more testing to the tor.rs file will really just be unit testing the torut library more than my code. I have attached the command I used to get a successful response when running this code as well:
> Tor endpoint http api

- teos/src/main.rs
Fixes a clippy issue in main where an async method was called while holding
the DB MutexGuard.
https://rust-lang.github.io/rust-clippy/master/index.html#await_holding_lock
> Fixes a clippy issue in main raised by rustc 1.61.0

- teos/proto/teos/appointment.proto
- teos/proto/teos/tower_services.proto
- teos/src/api/internal.rs
- teos/src/cli.rs
- teos/src/cli_config.rs
- teos/src/dbm.rs
- teos/src/responder.rs
- teos/src/watcher.rs
This PR adds a new command `get_appointments` to `teos-cli`.
A big chunk of `load_appointments_with_locator` and `load_trackers_with_locator` is repeated in `load_all_appointments` and `load_all_trackers` respectively, Should common parts be put together in new functions?
Closes #40
> feat: `get_appointments` cli command

- watchtower-plugin/src/main.rs
- watchtower-plugin/src/retrier.rs
Converts the retrier into an "object" and adds some minimal improvements, such as:
- minimize the amount of `lock().unwrap()`s for when accessing the `wt_client` to reduce the overhead.
- Create some tests contructors and contants to reduce the boilerplate
> Transforms the retrier into an object 

- watchtower-plugin/tests/pyproject.toml
- watchtower-plugin/tests/test.py
Some E2E test for the CLN plugin have conditional waits that may wait forever if the code has a bug. Set a timeout for an early fail so we don't have to waste CI time.
> Adds a timeout to Python tests that may wait forever

- teos-common/proto/common/teos/v2/user.proto
- teos-common/src/receipts.rs
- teos-common/src/test_utils.rs
- teos/src/api/internal.rs
- teos/src/dbm.rs
- teos/src/gatekeeper.rs
- teos/src/responder.rs
- teos/src/test_utils.rs
- teos/src/watcher.rs
- watchtower-plugin/src/dbm.rs
- watchtower-plugin/src/lib.rs
- watchtower-plugin/src/main.rs
- watchtower-plugin/src/retrier.rs
- watchtower-plugin/src/wt_client.rs
Fixes #76 
- Updates the protos to add an additional field `RegisterRequest`. Notice this is a breaking change. Previous protos won't work with this one.
- Updates the gRPC server to account for the updated protos
- Updates the database. The `users` table now also stores the `subscription_start` field. This is also a breaking change.
- Adds `subscription_start` to `UserInfo` in the `Gatekeeper`
- Sets constants in tests_utils to reduce the tests boilerplate
- Updates the database. `towers` does not store the `subscription_expiry` anymore (it was being stored both there an in the `subscription_receipt`). 
- The `subscription_start` field is added to `subscription_receipts` and the primary key updated from `tower_id` to `(tower_id, subscription_expiry)`.
- When info regarding a tower is …
> Add subscription_start to registration receipt

- teos/src/cli_config.rs
See https://github.com/talaia-labs/rust-teos/issues/62
cc @meryacine, let me know if I misunderstood the issue or if there are other fields I should work through in the CLI to fix as well!
```
rust-teos git:62*
λ ./target/debug/teos-cli get_user
error: The following required arguments were not provided:
<user_id>
USAGE:
teos-cli get_user <user_id>
For more information try --help
```
> change `rename_all` macro value to `snake_case` for user_id

- teos-common/src/lib.rs
- teos/src/lib.rs
Clippy for Rust 1.63.0 raises a lint warning regarding structures implementing
PartialEq but not Eq: https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
The autogenerated code from the common protos does fall into this constrain. However, the current recommended
solution from the `prost` team is to disable the check: https://github.com/tokio-rs/prost/issues/661
> Disable clippy::derive_partial_eq_without_eq in protos

- teos-common/build.rs
- teos-common/src/ser.rs
- teos/build.rs
- teos/src/api/http.rs
- watchtower-plugin/README.md
- watchtower-plugin/src/main.rs
From https://github.com/talaia-labs/rust-teos/pull/82#pullrequestreview-1059016422
> Adds getsubscriptioninfo to the CLN plugin

- watchtower-plugin/README.md
- watchtower-plugin/src/dbm.rs
- watchtower-plugin/src/main.rs
- watchtower-plugin/src/retrier.rs
- watchtower-plugin/src/wt_client.rs
- `abandontower <tower_id>` will remove all data associated with a given tower. If the tower is being retried, the retry strategy will be aborted on the next iteration.
- `getappointmentreceipt <tower_id> <locator>` will pull a given appointment receipt from the local database.
- `getregistrationreceipt <tower_id>` will pull the latest registration receipt from the local database.
- Add some optional parameters to `getregistrationreceipt` so a period can be specified. If present, the receipt matching that period will be pulled (if any).
> Adds some extra commands to the cln-plugin

- README.md
- teos/Cargo.toml
- teos/src/api/tor.rs
- teos/src/config.rs
- teos/src/main.rs
Persists the Tor secret to to `<teos_data_dir>/<network_dir>/onion_v3_sk` as suggested in #70.
Adds an additional trigger to the Tor task to signal when the service is ready. Otherwise the logs may show the tower being ready before the hidden service is reported:
```
[...]
2022-08-17T12:12:21.887Z INFO [teosd] Starting up hidden tor service
2022-08-17T12:12:21.887Z INFO [teosd] Tower ready
2022-08-17T12:12:21.888Z INFO [teos::api::tor] Loading Tor secret key from disk
2022-08-17T12:12:21.951Z INFO [teos::api::tor] onion service: 5ofdkbxqtfoerrqu2nh4h2zfkvpkvhompsrxgqxyowkdwegq2s5eqmyd.onion:2121
```
Close #70
> Persists Tor secret key to disk

- teos/src/main.rs
Given we cannot address #57 atm, lets at least make it so if the Tor thread fails it does so in a more user friendly way.
> Makes Tor task panics more user friendly

- watchtower-plugin/Cargo.toml
- watchtower-plugin/src/main.rs
- watchtower-plugin/src/net/http.rs
- watchtower-plugin/src/retrier.rs
- watchtower-plugin/src/wt_client.rs
Check if the tower address is an onion address and proxies it through Tor if so. 
This assumes Tor is running on the backend, which is the same assumption used by CoreLN AFAICT https://lightning.readthedocs.io/TOR.html
Close #92 #93
> Adds Tor support to cln-plugin

- teos/src/gatekeeper.rs
- teos/src/responder.rs
- teos/src/watcher.rs
Currently, `DBM::batch_remove_{appointments, users}` was being hit even if there was no data to delete. This also applied to trying to delete data from memory, but the latter was less of an issue.
While this was not a thread by itself (no data was actually being deleted), it was certainly wasteful.
> Avoid having to hit the db if there is no data to delete

- teos/src/api/http.rs
- teos/src/main.rs
In normal conditions, if the http API cannot bootstrap (due to the gRPC server being temporarily unavailable) it will just retry until it connects.
However, this is done asynchronously, meaning that it could be the case that the tower is reported as ready when it is actually not. This can be hit during E2E testing if the tower is restarted too quickly, resulting in a test failure:
https://github.com/sr-gi/rust-teos/runs/8074272734?check_suite_focus=true#step:9:5543
https://github.com/sr-gi/rust-teos/runs/8074272734?check_suite_focus=true#step:9:6970
> Adds a ready signal for the http API

- watchtower-plugin/tests/test.py
`watchtower-plugin::tests::test::test_watchtower` was not properly checking that an appointment could not be found after resolving. This was due to an off-by-one error that made the resolution not actually happen.
> Fixes E2E test test_watchtower

- .github/workflows/cln-plugin.yaml
- watchtower-plugin/src/dbm.rs
- watchtower-plugin/src/lib.rs
- watchtower-plugin/src/main.rs
- watchtower-plugin/src/retrier.rs
- watchtower-plugin/src/wt_client.rs
- watchtower-plugin/tests/conftest.py
- watchtower-plugin/tests/pyproject.toml
- watchtower-plugin/tests/test.py
The current implementation of the `cln-plugin` had a race condition where some pending appointments may be missed if they were added while the `Retrier` was trying to send some data to the tower.
The issue was discovered in #84, and goes as follows:
The `Retrier` used to load all the data from the database (in bulk) when starting a new retry and stored a copy of it to do the retry. This is somehow necessary since we cannot hold a reference of the data across futures. Therefore, if some data was added after the pending appointments were loaded, it would be missed.
The solution goes through different stages:
- First, the data is checked in memory and loaded one by one instead of in bulk.
- Second, the channel shared between the `WTClient` and the `Retrier` shares a `(tower_id, locator)` …
> Fixes race condition in #84

- teos/src/test_utils.rs
`with_height` test method might produce invalid blocks because, after #79, we can't create empty blocks any more, and some random txs might result in a not enough proof of work, thus making `at_height` (in #56) method panic when validating the produced blocks.
Fixes #56
> tests: Fix `at_height` may panic

- teos/src/api/http.rs
- teos/src/api/internal.rs
- teos/src/carrier.rs
- teos/src/responder.rs
- teos/src/test_utils.rs
- teos/src/watcher.rs
In many of the tests, a `BitcoindMock` was being created and, alongside it, a `jsonrpc-http` server started to receive `jsonrpc` request from the tower. However, these servers were never stopped after every individual test (only by the end of the test suite) resulting in a high number of opened file descriptors.
Turns out `jsonrpc-http-server::Server` has a `CloseHandle` that allows us to close the server from a different thread.
h/t to @erikarvstedt for pointing out the root of the issue.
> Fixes #119

- watchtower-plugin/src/retrier.rs
- watchtower-plugin/src/wt_client.rs
DBM doesn't need to wrapped in an `Arc<Mutex<` since `WTClient` is already wrapped in an `Arc<Mutex<` in all occurrences and DBM is neither `Copy` nor `Clone`.
> watchtower-plugin: get rid of unnecessary `Arc<Mutex<` in `WTClient`

- teos-common/Cargo.toml
- teos/Cargo.toml
- teos/src/cli_config.rs
- teos/src/config.rs
- watchtower-plugin/Cargo.toml
- watchtower-plugin/tests/pyproject.toml
Makes it so the .rs files pull the version info from the Cargo files so it is always consistent
> Bumps teos version to 0.1.2

- teos/Cargo.toml
chunked-transfer was used in an old version of the test suite for a custom HTTP server. The test server was removed in bbd3857c70e321f1a563036c11deb184d439fb3e, hence the dependency was never used from that point on.
> Removes chunked-transfer from deps

- watchtower-plugin/src/net/http.rs
Let's be less dramatic, especially given connection timeouts fall under this category.
cc/ @niftynei
> Change log level for failed post requests in CoreLN plugin

- teos/src/cli_config.rs
- teos/src/conf_template.toml
- teos/src/config.rs
- teos/src/main.rs
Splits debug logging into two options: `debug` and `deps_debug` so we don't need to log third-party stuff in debug mode if we don't really need to (which is the most usual case).
Also, remove `debug` from `teos-cli` given it was not being used.
> Fix third party logging

- .github/workflows/build.yaml
- .github/workflows/cln-plugin.yaml
- teos/src/extended_appointment.rs
GH seems to have changed the way caches are handled and the old action caches are gone. Our CLN cache does not build anymore with the old actions (things used to work due to the old cache being restored).
Some actions are using deprecated stuff, update them. The only missing thing to be updated is actions-rs/toolchail, but there is no new version of it.
This is already been tracked, but looks like the project is not maintained:
https://github.com/actions-rs/toolchain/issues/219
https://github.com/actions-rs/toolchain/issues/221
If this ends up being an issue, we can manually install rust: https://github.com/actions-rs/toolchain/issues/216#issuecomment-1291613319
> Updates actions

- DEPENDENCIES.md
- teos/src/carrier.rs
- teos/src/lib.rs
- teos/src/main.rs
- teos/src/responder.rs
- teos/src/test_utils.rs
- teos/src/tx_index.rs
- teos/src/watcher.rs
Generalizes the `Watcher`'s `LocatorCache` into a `TxIndex` that can be used both by the `Watcher` and the `Responder`. The former does use it in the same way as before (as a `LocatorCache` to keep track of the `Locators` of the last n blocks). As for the latter, it is used to implement a pruned transaction index (a `Txid`:`BlockHash` map).
By adding this `TxIndex` in the `Responder` we don't have to run `bitcoind` with `txindex=1` anymore and, therefore, we are able to reduce the initial storage requirements significantly: from ~420 GB on disk at the time of writing to a few dozen KB in memory.
With this new approach queries to past transactions will be performed internally instead of against `bitcoind` in most cases. If a transaction cannot be found in our index nor in mempool it'll …
> Implements an internal txindex so we don't have to run bitcoind with `txindex=1`

- teos/src/cli_config.rs
- watchtower-plugin/tests/test.py
Polled the userbase about snake case vs lower case. [The choice](https://twitter.com/sr_gi/status/1589576235730231299) was clear.
> Changes rpc commands naming from snake case to lower case

- teos/src/api/tor.rs
- teos/src/main.rs
Traffic routed trough Tor was being redirected to localhost indistinguishably of whether the public http API was being offered there or not. This made the tower unavailable (trough Tor) when it was being offered both in clearnet and Tor.
> Fixes tor proxy redirection

- teos/src/conf_template.toml
- teos/src/config.rs
Turns out both the clearnet API and the Tor hidden service can be run on the same port.
h/t @mariocynicys for realizing this was possible.
Related to #143
> Changes the onion hidden service port to match the clearnet API port

- INSTALL.md
- watchtower-plugin/README.md
Using --locked with cargo install(s) will instruct cargo to use the lock file in the repo (Cargo.lock). So all the users' builds will be identical to builds in the master branch.
> use --locked with cargo install

- .github/workflows/cln-plugin.yaml
- Cargo.lock
- watchtower-plugin/Cargo.toml
- watchtower-plugin/src/main.rs
- watchtower-plugin/tests/conftest.py
- watchtower-plugin/tests/pyproject.toml
- watchtower-plugin/tests/test.py
Includes the minimal changes to make the plugin compatible with the newest version of `cln-plugin`. This new version unblocks some pending improvements (https://github.com/talaia-labs/rust-teos/discussions/102) but those can be left as follow-ups.
Fixes #152
> Minimal changes to make the plugin compatible with cln-plugin 0.1.1

- watchtower-plugin/tests/conftest.py
This is adding a fixed sleep to `watchtower-plugin::tests` given they may still fail due to `TeosD` not having enough time to bootstrap after the log check was temporarily removed. 
Rationale: https://github.com/talaia-labs/rust-teos/issues/156#issuecomment-1326555685
Notice this is temporary and should be removed once #156 is addressed.
> Adds a fixed sleep so `TeosD` has time to bootstrap in the `watchtower-plugin` tests

- teos-common/src/lib.rs
- teos-common/src/net.rs
- teos/build.rs
- teos/proto/teos/v2/tower_services.proto
- teos/src/api/internal.rs
- teos/src/api/mod.rs
- teos/src/api/serde.rs
- teos/src/api/tor.rs
- teos/src/main.rs
- teos/src/test_utils.rs
This PR adds a new field to the `gettowerinfo` RPC call. The field includes data regarding the interfaces where the public API is being offered (i.e. ipv4 and/or tor).
The rationale for this is having the API endpoint information handy without having to check the logs (this is currently most relevant for the onion address).
Fixes https://github.com/talaia-labs/rust-teos/issues/143
cc/ @jochemin
> Adds addresses field to `gettowerinfo`

- watchtower-plugin/src/retrier.rs
> Removes redundant sanity check for Retrier::start

- watchtower-plugin/src/main.rs
On failed fresh register the client was trying to set the tower status of an unknown tower. This was generating a `**BORKEN**` log in `lightningd`'s logs.
Adds an additional check for register to prevent this.
> Avoids setting the state of unregistered towers

- watchtower-plugin/src/net/http.rs
> Replace server.address() by server.base_url()

- watchtower-plugin/src/convert.rs
- watchtower-plugin/src/dbm.rs
- watchtower-plugin/src/lib.rs
- watchtower-plugin/src/main.rs
- watchtower-plugin/src/net/http.rs
- watchtower-plugin/src/retrier.rs
- watchtower-plugin/src/wt_client.rs
Some `Strings` could be replaced by `&str` and some calls made more explicit.
> Minor improvements regarding Strings in cln-plugin

- teos-common/src/receipts.rs
- watchtower-plugin/src/dbm.rs
- watchtower-plugin/src/lib.rs
- watchtower-plugin/src/main.rs
- watchtower-plugin/src/net/http.rs
- watchtower-plugin/src/retrier.rs
- watchtower-plugin/src/wt_client.rs
The current version of the `watchtower-plugin` does not auto-renew subscriptions once they expire or get out of appointment slots. This may be annoying and some users may even be unaware that the data is not being back-up anymore due to the subscription needing a renewal. 
This PR fixes this. The approach for the fix is to use the `Retirer` for it given the logic for unreachable towers and towers with a subscription issue was pretty similar. The way this works from now on is the following:
If an appointment is sent to the tower and there is a subscription error, the data is added to pending, the tower is flagged as `subscription_error` and the `Retrier` is notified (so far nothing changed). The `Retirer` will now try to renew the subscription if the state of the tower is …
> Implements auto-register for the watchtower-client

- teos-common/src/lib.rs
- watchtower-plugin/src/convert.rs
- watchtower-plugin/src/net/http.rs
CoreLN supports named parameters for their RPC commands when passing `-k` to the call. e.g:
`lightning-cli -k <command> arg_0=val_0...arg_n=val_n`
Add support for our plugin so it's easier to tackle #69
> Adds named arguments to CoreLN plugin

- teos/src/api/http.rs
- teos/src/api/internal.rs
- teos/src/config.rs
- teos/src/watcher.rs
- watchtower-plugin/src/lib.rs
- watchtower-plugin/src/main.rs
- watchtower-plugin/src/retrier.rs
- watchtower-plugin/src/wt_client.rs
- watchtower-plugin/tests/test.py
The current version of the `watchtower-plugin` for CLN will try to re-send data to towers that are not reachable for various reasons using an exponential backoff strategy. However, once the strategy is given up on, the tower will be flagged as unreachable and not further retried (unless the user manually triggers it through the `retrytower` rpc).
This PR adds auto-retry logic, so once a specific unreachable tower is given up on, the retrier is not removed but remains idle and it's launched again after a specific delay (controlled by the `watchtower-auto-retry-delay`). From this point on, retriers will only be removed from the `RetryManager` is they fail due to a permanent error, but not due to a transient one (in which case they will be auto-retried).
In order to achieve this, the …
> Adds auto-retry logic to watchtower-plugin

- Cargo.lock
- watchtower-plugin/Cargo.toml
Commits this standalone so #170 does not need to build on top of #160 (which was the original PR that bumped the cln-plugin version).
> Bumps cln-plugin version to v0.1.2 in watchtower-plugin

- watchtower-plugin/src/constants.rs
- watchtower-plugin/src/lib.rs
- watchtower-plugin/src/main.rs
- watchtower-plugin/src/retrier.rs
Options include helper functions to convert them to their proper type after
`cln-plugin=0.1.2`. Use that to reduce the option parsing boilerplate.
Also move all names, descriptions and default values for options, rpc_methods and hooks
to a new file.
> Simplifies the cln plugin option parsing

- teos-common/src/net.rs
- watchtower-plugin/src/lib.rs
- watchtower-plugin/src/main.rs
- watchtower-plugin/src/net/http.rs
- watchtower-plugin/src/net/mod.rs
- watchtower-plugin/src/retrier.rs
- watchtower-plugin/src/wt_client.rs
- watchtower-plugin/tests/conftest.py
- watchtower-plugin/tests/test.py
The `watchtower-plugin` was specifying a custom tor flag to signal whether Tor may be used by the client. This was due to `cln-plugin (v0.1.1-)` not allowing plugins to access the CoreLN configuration options and, therefore, our plugin was unable to fetch the `proxy` / `always-use-proxy` options.
This fetches the aforementioned options and revamps the logic to comply with the `always-use-proxy` requirements, that is, if the flag is set all communications must be performed using Tor. Also, it replaces some of the currently used `String`s for more meaningful types to store network data (such as `AddressType`, `NetAddress`, or `ProxyInfo`).
This drops our custom `watchtower-proxy` config option
> Improves tor flag logic in watchtower-plugin

- teos-common/src/net/http.rs
- teos-common/src/net/mod.rs
- teos/src/api/http.rs
- watchtower-plugin/src/main.rs
- watchtower-plugin/src/net/http.rs
- watchtower-plugin/src/retrier.rs
Useful for both the tower API and the clients.
This is currently building on top of #160, so we'll need to merge that first.
> Defines Endpoint enum to avoid using hardcoded strings as endpoints

- INSTALL.md
- contrib/init/README.md
- contrib/init/teosd.service
This builds on top of the work from the work by @decentralizedb and @jochemin in #138. It is mainly just re-arranging the code and readmes to fit https://github.com/talaia-labs/rust-teos/pull/138#pullrequestreview-1195570409, but they did all the heavy lifting.
Close #138
> Adds teosd.service to run teos as daemon

- teos/src/api/http.rs
- teos/src/api/internal.rs
Also updates the severity from the http logs from info to debug
> Adds debug logs to RPC requests and improves the ones for the http interface

- watchtower-plugin/src/retrier.rs
The pooling time for the Retrier was hardcoded to 1, let's at least use a constant for that.
Also, `retrier::tests::test_manage_retry_while_idle` was randomly failing (for Ubuntu) when checking whether the Retrier was idle after giving up on a retry. This is due to the time of running a round not being taken into account.
~~Turns out this is super brittle, so I'm going to modify the timers as little as possible for now.~~
Many timers have been modified to make actual sense.
Superseeds #182 (Close #182)
Edit:
@mariocynicys found why this was brittle in https://github.com/talaia-labs/rust-teos/pull/184#issuecomment-1405635662, looks like it isn't anymore 😄
> Defines Retrier polling waiting time as a constant and fixes tests

- contrib/init/teosd.service
- teos/src/main.rs
Updates `teosd.service` to add `tor.service` to `Wants=`, so it waits for tor to be initialized if it has to.
Will keep this open for now though, more modifications may pop up while testing v0.2.0-rc1.
> Updates teosd.service

- teos/src/main.rs
Use `conf.onion_hidden_service_port`.
Closes #186 
cc/ @1010adigupta
> fixup: record the correct port for the Tor interface

- teos-common/src/appointment.rs
- teos-common/src/lib.rs
- teos-common/src/net/http.rs
- teos-common/src/net/mod.rs
- teos/src/api/http.rs
- teos/src/api/internal.rs
- teos/src/api/tor.rs
- teos/src/bitcoin_cli.rs
- teos/src/carrier.rs
- teos/src/chain_monitor.rs
- teos/src/cli.rs
- teos/src/config.rs
- teos/src/dbm.rs
- teos/src/main.rs
- teos/src/responder.rs
- teos/src/tls.rs
- teos/src/tx_index.rs
- teos/src/watcher.rs
- watchtower-plugin/src/convert.rs
- watchtower-plugin/src/dbm.rs
- watchtower-plugin/src/main.rs
- watchtower-plugin/src/net/http.rs
- watchtower-plugin/src/retrier.rs
- watchtower-plugin/src/wt_client.rs
The rule of thumb seems to be (at least for now):
- No method / function calls
- No arithmetic operations
- No field access (foo.bar)
- No package access (foo::bar)
- Some additional limitations for `panic` (such as using a match variant)
This is due to clippy complaining about some, so I went ahead and updated all the ones I've seen.
> Formats strings to use inline params when possible

- teos/src/api/http.rs
- teos/src/main.rs
This is a pretty simple PR, but it was hurting my eyes seeing that much replication and weird variable naming with respect to the internal API.
In a nutshell, this simply makes `http::serve` take `grpc_bind` as `SocketAddr` instead of `String`, so we can get rid of a useless variable and rename things more accordingly.
> Makes http::serve take a SockAddr instead of a starting

- Cargo.lock
- watchtower-plugin/Cargo.toml
- watchtower-plugin/src/net/http.rs
- watchtower-plugin/src/retrier.rs
This PR replaces our current mock for the API's HTTP interface ([httpmock](https://crates.io/crates/httpmock)) by [mockito](https://crates.io/crates/mockito)). The main reason for replacing one with the other is that the latter is more actively maintained and developed on, apart from it having some functionality that would be useful for us but the former lacked.
On top of that, `httpmock` was the root of some issues that we had worked around but were still carrying, such as #119 and #165.
It needs to be noted that, currently, we have replaced some of out time-based wait-and-check for the `Retrier` with some loops waiting for a condition to be met. This is due to `mockito` having some unexpected behavior for API delays when tests are run in parallel. Notice how this was also an issue with …
> Replaces httpmock with mockito

- teos/src/responder.rs
The conversion was triggering https://rust-lang.github.io/rust-clippy/master/index.html#useless_conversion
> Removes unnecessary `into_iter` from Responder tests

- teos/src/cli.rs
Let's not just spit a debug error when calling `teos-cli` pointing to an unreachable backend.
> Makes teos-cli cannot connect to backend error message more friendly

- teos/src/config.rs
- teos/src/main.rs
If a tower hasn't been running for a long time and the backend runs in pruned mode it could be the case that by the time the tower comes back online, the Last known block by the tower is not being known by the node anymore. In this situation, the tower cannot bootstrap normally, given the cache cannot be populated.
This commits adds a new argument to teosd (`--forceupdate`) that can be used to force a tower to update its last known block to the earliest known block by the backend under this situation. Notice that doing so may make the tower miss some of its state transitions (the ones triggered by missed blocks), so this must be done as a last resource.
Fixes #209 
Supersedes #212 
This can be tested easily in regtest by running `bitcoind` with the (hidden, undocumented) `-fastprune` …
> Adds --forceupdate to teosd

- watchtower-plugin/tests/test.py
Currently, when mocking sendrawtransaction so it does nothing, the client will raise an exception given the picked lambda does not accept any params (and sendrawtransaction has some). Patches it so this does not happen.
This patch is pretty minimal, given the behavior wrt CLN does not change, but it feels better not to except here.
> Properly patches sendrawtransaction so it does not crash

- teos/src/cli.rs
Some CLI errors were printed using ``println!`` , causing them to be indistinguishable from regular output. To resolve this, the code has been updated to use ``eprintln!`` and ``exit code 1`` for error messages. By printing errors to the standard error, error messages are now clearly separated from regular output.
> Fix error handling in CLI

- .github/workflows/build.yaml
Fixes #230 
**Description**
This PR adds a new job in the CI that checks the formatting of Python files using Black. This ensures that all Python files follow the same code styling guidelines, making the codebase cleaner and easier to read.
**Changes**
1. Modified `.github/workflows/build.yaml` to include a new job for Black checks.
Please let me know if any changes are required.
> Add black check to Python files in CI

- teos-common/src/test_utils.rs
- teos/src/api/http.rs
- teos/src/api/internal.rs
- teos/src/dbm.rs
- teos/src/extended_appointment.rs
- teos/src/gatekeeper.rs
- teos/src/main.rs
- teos/src/responder.rs
- teos/src/test_utils.rs
- teos/src/tx_index.rs
- teos/src/watcher.rs
Just by loading the minimal necessary data plus dropping the `last_known_blocks` we get a huge reduction (2GB -> 1.2GB for 2.2M appointments*).
We can even do better and further reduce the data stored in memory (dropping user_ids and potentially locators).
<sup>* This is on MacOS. On linux we get to as low as 1.3G but only 1.0G is actually being used, we know that because if we call `malloc_trim` we get to 1.0G</sup>
Fixes #224
> optimizing memory usage

- teos/src/tx_index.rs
- teos/src/watcher.rs
- watchtower-plugin/src/convert.rs
Clippy is complaining about using `.get(0)` instead of `.fist()` in methods where we are getting more than just the first item. Supress the warning
> plugin: patches clippy

- watchtower-plugin/tests/pyproject.toml
`pyln-testing` depends on `pyln-client`, and the API for the latter has changed in version 24.0. Fix our dependency to 23.11 to prevent test from breaking.
I'm not really sure why an old version of `pyln-testing` tries to download the newest version of `pyln-client` as dependency, but whatever
> watchtower-plugin: fixes pyln-client version

- teos/src/bitcoin_cli.rs
- teos/src/conf_template.toml
- teos/src/config.rs
- teos/src/main.rs
Currently, we are authenticating against bitcoind using user/pass. This adds the option to use a cookie file instead.
Notice providing the two authentication methods at the same time is not permitted, users must set either the user/pass pair or the cookie file path.
Close #246
> Adds rpccookie to bitcoind auth methods

- .github/workflows/build.yaml
- .github/workflows/cln-plugin.yaml
- watchtower-plugin/src/retrier.rs
- watchtower-plugin/tests/conftest.py
- watchtower-plugin/tests/pyproject.toml
- watchtower-plugin/tests/test.py
Replaces #255 
I think in your PR tests ran slow because you were running them on an ancient pyln-testing version. Just to make sure i added VALGRIND=0 as that can cause huge slowdowns but i don't know when valgrind actually runs in these tests.
I also assume you don't want CI to run on anything else than commit to the master branch. While testing with a PR all CI ran both for the feature branch and the PR kinda weird.
Also `developer: None` is not needed with a modern `pyln-testing` version, as that is a default setting.
> modernize cln tests and CI

- .github/workflows/build.yaml
- .github/workflows/cln-plugin.yaml
- Cargo.lock
- Cargo.toml
- teos-common/Cargo.toml
- teos/Cargo.toml
- teos/src/cli.rs
- teos/src/tls.rs
- watchtower-plugin/Cargo.toml
rcgen was using version 0.8 which used a ring version that didn't support ppc64le arch. Support for it was recently added in ring=0.17.0 and supported by rcgen in 0.12
tonic also had a chain dependency to ring, so it needed updating (and therefore also prost) 
Close #243
> Bumps dependencies to get rid old version of ring (<0.17)

- coffee.yml
Core lightning is starting to support a decent plugin manager that gives you the possibility to install a plugin without care about the process.
Coffee [1] is a plugin manager that uses the manifest like all basic plugin managers (npm, pacman ...).
So this commit is adding support for coffee and allowing people to install plugins with the following command:
```
coffee remote add teos-git https://github.com/talaia-labs/rust-teos.git
coffee install rust-teos -v
coffee list
```
[1] https://github.com/coffee-tools/coffee
> meta: add possibility to install cln plugin with coffee

- .github/workflows/cln-plugin.yaml
Compiling time with rustc over 1.80.0 (inclusive) results in a crash for old versions of the time crate, which CLN uses. Make sure we are up to date with the current revision
> Makes `time` is up to date when compiling CLN for CI jobs

- watchtower-plugin/src/main.rs
> plugin: replaces map_err for inspect_err in cases where we were only logging and returning
